services:
  grpc_base:
    build:
      context: ../.
      dockerfile: docker/grpc_base.Dockerfile
      network: host
      target: grpc_base
      args:
        UBUNTU_DISTRO: $UBUNTU_DISTRO
    image: grpc_bridge_base:${UBUNTU_DISTRO:-jammy}
    profiles: [base]

  ros_bridge:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      network: host
      ssh: 
        - default
      args:
        SIDE_A_UBUNTU: $ROS_BRIDGE_GRPC_SIDE_A_UBUNTU
        SIDE_A_DISTRO: $ROS_BRIDGE_GRPC_SIDE_A_DISTRO
        USER_SIDE_A_REPOS: $ROS_BRIDGE_GRPC_USER_SIDE_A_REPOS
        SIDE_B_UBUNTU: $ROS_BRIDGE_GRPC_SIDE_B_UBUNTU
        SIDE_B_DISTRO: $ROS_BRIDGE_GRPC_SIDE_B_DISTRO
        USER_SIDE_B_REPOS: $ROS_BRIDGE_GRPC_USER_SIDE_B_REPOS
        SYSTEM_PACKAGES: $ROS_BRIDGE_GRPC_SYSTEM_PACKAGES
        CUSTOM_PACKAGES: $ROS_BRIDGE_GRPC_CUSTOM_PACKAGES
        ALLOWED_TYPES: $ROS_BRIDGE_GRPC_ALLOWED_TYPES
        MESSAGE_PACKAGES: $ROS_BRIDGE_GRPC_MESSAGE_PACKAGES
        COMPAT_OVERRIDES: $ROS_BRIDGE_GRPC_COMPAT_OVERRIDES
        BRIDGE_TYPE: $ROS_BRIDGE_GRPC_BRIDGE_TYPE
    image: ros_bridge_grpc
    container_name: ros_bridge_grpc_container
    tty: true
    stdin_open: true
    volumes:
      - ${ROS_BRIDGE_RUNTIME_CONFIG:-/dev/null}:/ros_params.yaml
      - /tmp
      - ${CYCLONEDDS_URI:-/dev/null}:/cyclonedds_uri.xml
      - ./fastrtps_default_profile.xml:/root/fastrtps_default_profile.xml
      - ${FASTDDS_DEFAULT_PROFILES_FILE:-/dev/null}:${FASTDDS_DEFAULT_PROFILES_FILE:-/dev/null}
      - ${FASTRTPS_DEFAULT_PROFILES_FILE:-/dev/null}:${FASTRTPS_DEFAULT_PROFILES_FILE:-/dev/null}
    network_mode: host
    pid: host
    ipc: host
    profiles: [none]

  side_b_introspection:
    extends: ros_bridge
    image: ros_bridge:$ROS_BRIDGE_GRPC_SIDE_B_DISTRO
    container_name: ros_bridge_b_${ROS_BRIDGE_GRPC_SIDE_B_DISTRO}_introspection
    build:
      target: side_b_ros_base
    env_file:
      - ./../config/side_b.env
    profiles: [dev]

  side_b_bridge:
    extends: side_b_introspection
    container_name: ros_bridge_b_${ROS_BRIDGE_GRPC_SIDE_B_DISTRO}
    build:
      target: side_b_build
    entrypoint: /entrypoints/run_ros_bridge.bash
    profiles: [runtime, all]

  side_a_introspection:
    extends: ros_bridge
    image: ros_bridge:$ROS_BRIDGE_GRPC_SIDE_A_DISTRO
    container_name: ros_bridge_a_${ROS_BRIDGE_GRPC_SIDE_A_DISTRO}_introspection
    build:
      target: side_a_ros_base
    env_file:
      - ./../config/side_a.env
    profiles: [dev]

  side_a_bridge:
    extends: side_a_introspection
    container_name: ros_bridge_a_${ROS_BRIDGE_GRPC_SIDE_A_DISTRO}
    build:
      target: side_a_build
    entrypoint: /entrypoints/run_ros2_bridge.bash
    profiles: [runtime, all]

  extract_generated:
    extends: ros_bridge
    container_name: ros_bridge_extract_generated
    build:
      target: side_b_ros_base
    command: ["cp", "-r", "/generated/", "/export/generated/"]
    volumes:
      - ./generated:/export/generated
    profiles: [all]

  side_b_bridge_dev:
    extends: side_b_introspection
    container_name: side_b_bridge_dev
    build:
      target: side_b_bridge_dev
    entrypoint: /bin/bash
    security_opt:
      # handle errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # disable QT-X11 memory sharing for RViz
      - QT_X11_NO_MITSHM=1
      # other environment variables...
    volumes:
      # bind the Xauthority file to use X11 forwarding
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority
      # other volumes...
      # - ../misc:/catkin_ws/misc       # optional local directory to mount files
    profiles: [dev]

  side_a_bridge_dev:
    extends: side_a_introspection
    container_name: side_a_bridge_dev
    build:
      target: side_a_bridge_dev
    entrypoint: /bin/bash
    security_opt:
      # handle errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # disable QT-X11 memory sharing for RViz
      - QT_X11_NO_MITSHM=1
    volumes:
      # bind the Xauthority file to use X11 forwarding
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority
      # other volumes...
      # - ../misc:/catkin_ws/misc       # optional local directory to mount files
    profiles: [dev]
