services:
  ros_bridge:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      ssh: 
        - default
      args:
        ROS1_DISTRO: $ROS_BRIDGE_GRPC_ROS1_DISTRO
        ROS2_DISTRO: $ROS_BRIDGE_GRPC_ROS2_DISTRO
        ROS2_UBUNTU: $ROS_BRIDGE_GRPC_ROS2_UBUNTU
        SYSTEM_PACKAGES: $ROS_BRIDGE_GRPC_SYSTEM_PACKAGES
        USER_ROS1_REPOS: $ROS_BRIDGE_GRPC_USER_ROS1_REPOS
        USER_ROS2_REPOS: $ROS_BRIDGE_GRPC_USER_ROS2_REPOS
        CUSTOM_PACKAGES: $ROS_BRIDGE_GRPC_CUSTOM_PACKAGES
        ALLOWED_TYPES: $ROS_BRIDGE_GRPC_ALLOWED_TYPES
        MESSAGE_PACKAGES: $ROS_BRIDGE_GRPC_MESSAGE_PACKAGES
        COMPAT_OVERRIDES: $ROS_BRIDGE_GRPC_COMPAT_OVERRIDES
    image: ros_bridge_grpc
    container_name: ros_bridge_grpc_container
    tty: true
    stdin_open: true
    volumes:
      - ${ROS_BRIDGE_RUNTIME_CONFIG:-/dev/null}:/ros_params.yaml
      - /tmp:/tmp
    network_mode: host
    pid: host
    ipc: host
    profiles: [all]

  ros1_bridge_introspection:
    extends: ros_bridge
    image: ros1_bridge:$ROS_BRIDGE_GRPC_ROS1_DISTRO
    container_name: ros1_bridge_${ROS_BRIDGE_GRPC_ROS1_DISTRO}_introspection
    build:
      target: ros1_base
    environment:
      - ROS_MASTER_URI
      - ROS_HOSTNAME

  ros1_bridge:
    extends: ros1_bridge_introspection
    container_name: ros1_bridge_${ROS_BRIDGE_GRPC_ROS1_DISTRO}
    build:
      target: ros1_build
    entrypoint: /entrypoints/run_ros1_bridge.bash
    profiles: [runtime, all]

  ros2_bridge_introspection:
    extends: ros_bridge
    image: ros2_bridge:$ROS_BRIDGE_GRPC_ROS2_DISTRO
    container_name: ros2_bridge_${ROS_BRIDGE_GRPC_ROS2_DISTRO}_introspection
    build:
      target: ros2_generated
    volumes:
      - ${CYCLONEDDS_URI:-/dev/null}:/cyclonedds_uri.xml
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI=/cyclonedds_uri.xml

  ros2_bridge:
    extends: ros2_bridge_introspection
    container_name: ros2_bridge_${ROS_BRIDGE_GRPC_ROS2_DISTRO}
    build:
      target: ros2_build
    entrypoint: /entrypoints/run_ros2_bridge.bash
    profiles: [runtime, all]

  extract_generated:
    extends: ros_bridge
    container_name: ros1_bridge_extract_generated
    build:
      target: ros1_base
    command: ["cp", "-r", "/generated/", "/export/generated/"]
    volumes:
      - ./generated:/export/generated
    profiles: [all]

  ros1_bridge_dev:
    extends: ros1_bridge_introspection
    container_name: ros1_bridge_dev
    build:
      target: ros1_bridge_dev
    entrypoint: /bin/bash
    security_opt:
      # handle errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # disable QT-X11 memory sharing for RViz
      - QT_X11_NO_MITSHM=1
      # other environment variables...
    volumes:
      # bind the Xauthority file to use X11 forwarding
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority
      # other volumes...
      # - ../misc:/catkin_ws/misc       # optional local directory to mount files
    profiles: [dev, all]

  ros2_bridge_dev:
    extends: ros2_bridge_introspection
    container_name: ros2_bridge_dev
    build:
      target: ros2_bridge_dev
    entrypoint: /bin/bash
    security_opt:
      # handle errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # disable QT-X11 memory sharing for RViz
      - QT_X11_NO_MITSHM=1
    volumes:
      # bind the Xauthority file to use X11 forwarding
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority
      # other volumes...
      # - ../misc:/catkin_ws/misc       # optional local directory to mount files
    profiles: [dev, all]
