FROM ros:humble-ros-base AS ros2_base

# Install python and protoc

# Copy user packages into the image

# Install dependencies and build all message types

# Generate proto files

# Compile proto files

# Generate C++ source code to translate between proto and ROS