ros1_distro: noetic
ros2_distro: humble

msg_packages:
    std_msgs:
        - String

    tf2_msgs: [ALL]

    geometry_msgs:
        - [ALL]

    sensor_msgs:
        - PointCloud2

    moveit_msgs:
        - JointLimits
        - SolidPrimitive

custom_packages:
    - {package_name: my_package,
       ros1_url: "https://github.com/my_org/my_package.git -b noetic",
       ros2_url: "https://github.com/my_org/my_package.git -b humble"}
    - {package_name: my_other_package,
       ros1_url: "git@github.com:my_org/my_other_package.git",
       ros2_url: "git@github.com:my_org/my_other_package.git -b ros2"}
    - {package_name: local_package,
       ros1_path: "/local/path/to/my/awesome/ros1/interface_package",
       ros2_path: "/local/path/to/my/awesome/ros2/interface_package"}
    - {package_name: local_package_dependency,
       ros1_path: "/local/path/to/my/non_rosdep/ros1/interface/package/dependency",
       ros2_path: "/local/path/to/my/non_rosdep/ros2/interface/package/dependency"}

compatibility_overrides:
    - "std_msgs/Header"             # Has seq field in ROS1 but not in ROS2
    - "shape_msgs/SolidPrimitive"   # Has new enum constants added in ROS2
    - "moveit_msgs/JointLimits"     # Has jerk related fields in ROS2 but not ROS1
