side_A_distro: jazzy # side_A must always be ROS2
side_B_distro: noetic

packages:
   std_msgs/msg: [String]
   tf2_msgs/msg: [ALL]
   geometry_msgs/msg: [PoseWithCovarianceStamped]
   sensor_msgs/msg: [PointCloud2, Image, CameraInfo, JointState]
   moveit_msgs/msg: [JointLimits, SolidPrimitive]
   std_srvs/srv: [Trigger, SetBool]
   bridge_interface_example/srv: [ALL]

custom_packages:
   - {package_name: bridge_interface_example,
      side_A_path: ./../ros2/bridge_interface_example,
      side_B_path: ./../ros1/bridge_interface_example}

   - {package_name: moveit_msgs,
      side_A_url: https://github.com/moveit/moveit_msgs.git -b ros2,
      side_B_url: https://github.com/moveit/moveit_msgs.git -b master}

compatibility_overrides:
   - "std_msgs/msg/Header"              # Has seq field in ROS1 but not in ROS2
   - "shape_msgs/msg/SolidPrimitive"    # Has new enum constants added in ROS2
   - "moveit_msgs/msg/JointLimits"      # Has jerk related fields in ROS2 but not ROS1
   - "moveit_msgs/srv/GetCartesianPath" # Introduced a new link speed limit field in ROS2 iron  
   - "moveit_msgs/msg/MoveItErrorCodes" # Introduced a new message and source fields in ROS2 jazzy
